description: Club de robotique jurassien
url: "https://robots-ju.ch"

markdown: kramdown
permalink: /:year/:month/:day/:title
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post

gems:
  - jekyll-feed
  - jekyll-redirect-from
exclude:
  - Gemfile
  - Gemfile.lock

main_menu:
  - title: Home
    url: /
  - title: Photos
    url: /photos
  - title: Ateliers FLL
    url: /ateliers-fll
  - title: Ateliers Java
    url: /ateliers-java
  - title: Événements
    url: /events
  - title: Projets
    url: /projects
  - title: Palmarès
    url: /palmares
  - title: À propos
    url: /about
  - title: Contact
    url: /contact
