description: Club de robotique jurassien
url: "https://robots-ju.ch"

markdown: kramdown
excerpt_separator: <!--more-->
permalink: /:year/:month/:day/:title
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post

future: true

collections:
  - projects

gems:
  - jekyll-feed
  - jekyll-redirect-from
exclude:
  - Gemfile
  - Gemfile.lock

main_menu:
  - title: FLL Challenge
    url: /ateliers-fll
    atelier: 1
  - title: FLL Explore
    url: /ateliers-fll-explore
    atelier: 1
  - title: Avancés
    url: /ateliers-avances
    atelier: 1
  - title: Événements
    url: /events
  - title: Outils
    url: /outils
  - title: Palmarès
    url: /palmares
  - title: À propos
    url: /about
  - title: Contact
    url: /contact

sitemap:
  activities:
    - title: Ateliers FLL Challenge
      url: /ateliers-fll
    - title: Ateliers FLL Explore
      url: /ateliers-fll-explore
    - title: Ateliers Avancés
      url: /ateliers-avances
    - title: Coupe Robots-JU
      url: https://coupe.robots-ju.ch/
    - title: Événements
      url: /events
  pages:
    - title: Accueil
      url: /
    - title: Outils
      url: /outils
    - title: Palmarès
      url: /palmares
    - title: On parle de nous
      url: /presse
    - title: À propos
      url: /about
    - title: Sponsoring
      url: /sponsoring
    - title: Contact
      url: /contact

social_links:
  - title: Twitter/X
    url: https://twitter.com/RobotsJU
    label: "@RobotsJU"
    icon: twitter
  - title: Facebook
    url: https://www.facebook.com/RobotsJU/
    label: "@RobotsJU"
    icon: facebook
  - title: Instagram
    url: https://www.instagram.com/robotsju/
    label: "robotsju"
    icon: instagram
  - title: YouTube
    url: https://www.youtube.com/user/robotsju
    label: /robotsju
    icon: youtube-play
  - title: Flickr
    url: https://www.flickr.com/photos/robots-ju/
    label: "robots-ju"
    icon: flickr
  - title: GitHub
    url: https://github.com/robots-ju
    label: "robots-ju"
    icon: github
  - title: LinkedIn
    url: https://www.linkedin.com/company/robots-ju/
    label: "robots-ju"
    icon: linkedin

contact_form_url: https://forms.robots-ju.ch/forms/site-contact
