name: Miniatures images presse

on:
  push:
    branches:
      - master

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run PHP script
        run: php _scripts/presse-thumbnails.php

      - name: Commit new files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Ajout miniatures presse" || echo "No changes to commit"
          git push
